version: '3.8'

services:
  pose-app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: pose-classification
    ports:
      - "8501:8080"
    environment:
      - STREAMLIT_SERVER_PORT=8080
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    mem_limit: 1.5g
    cpus: 1.0

networks:
  default:
    driver: bridge
